language: android
jdk: oraclejdk8
os: linux
dist: xenial
env:
    global:
        - ANDROID_API_LEVEL=29
        - ANDROID_BUILD_TOOLS_VERSION=29.0.2
android:
    components:
        - tools
        - platform-tools
        - tools
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION
        - android-$ANDROID_API_LEVEL
        # Additional components
        - extra-android-m2repository

before_script:
    - chmod +x gradlew
    - chmod +x cicd_scripts/lint-up.rb
    - curl -sSL "https://github.com/facebook/infer/releases/download/v1.0.0/infer-linux64-v1.0.0.tar.xz" | sudo tar -C /opt -xJ && sudo ln -s "/opt/infer-linux64-v1.0.0/bin/infer" /usr/local/bin/infer

script:
    - ./gradlew clean assembleDebug
    - ruby cicd_scripts/lint-up.rb
    - ./gradlew clean
    - infer run -- ./gradlew build
